import ModuleInstance from './index.js'

export default function updateVariableDefinitions(self: ModuleInstance): void {
	self.setVariableDefinitions([
		{ variableId: 'aperture', name: 'Aperture' },
		{ variableId: 'aperture_control', name: 'Aperture Control' },
		// CDL Variables
		{ variableId: 'cdl_power_r', name: 'CDL Power R' },
		{ variableId: 'cdl_power_g', name: 'CDL Power G' },
		{ variableId: 'cdl_power_b', name: 'CDL Power B' },
		{ variableId: 'cdl_slope_r', name: 'CDL Slope R' },
		{ variableId: 'cdl_slope_g', name: 'CDL Slope G' },
		{ variableId: 'cdl_slope_b', name: 'CDL Slope B' },
		{ variableId: 'cdl_offset_r', name: 'CDL Offset R' },
		{ variableId: 'cdl_offset_g', name: 'CDL Offset G' },
		{ variableId: 'cdl_offset_b', name: 'CDL Offset B' },
		{ variableId: 'cdl_saturation', name: 'CDL Saturation' },

		{ variableId: 'iso', name: 'ISO' },
		{ variableId: 'white_balance', name: 'White Balance' },
		{ variableId: 'shutter', name: 'Shutter' },
		{ variableId: 'sensor_frame_rate', name: 'Sensor Frame Rate' },
		{ variableId: 'sensor_format', name: 'Sensor Format' },
		{ variableId: 'active_power_source', name: 'Active Power Source' },
		{ variableId: 'af', name: 'Autofocus' },
		{ variableId: 'af_mode', name: 'Autofocus Mode' },
		{ variableId: 'af_position', name: 'Autofocus Position' },
		{ variableId: 'af_size', name: 'Autofocus Size' },
		{
			variableId: 'audio_external_left_gain',
			name: 'Audio External Left Gain',
		},
		{
			variableId: 'audio_external_right_gain',
			name: 'Audio External Right Gain',
		},
		{
			variableId: 'audio_external_link_gain',
			name: 'Audio External Link Gain',
		},
		{ variableId: 'audio_headphone_mute', name: 'Audio Headphone Mute' },
		{ variableId: 'audio_headphone_source', name: 'Audio Headphone Source' },
		{ variableId: 'audio_input_type_ch3', name: 'Audio Input Type CH3' },
		{ variableId: 'audio_input_type_ch4', name: 'Audio Input Type CH4' },
		{
			variableId: 'audio_internal_left_gain',
			name: 'Audio Internal Left Gain',
		},
		{
			variableId: 'audio_internal_right_gain',
			name: 'Audio Internal Right Gain',
		},
		{
			variableId: 'audio_internal_link_gain',
			name: 'Audio Internal Link Gain',
		},
		{ variableId: 'audio_source', name: 'Audio Source' },
		{ variableId: 'beep_enable', name: 'Beep Enable' },
		{ variableId: 'beep_record_start', name: 'Beep Record Start' },
		{ variableId: 'beep_record_stop', name: 'Beep Record Stop' },
		{ variableId: 'camera_firmware_version', name: 'Camera Firmware Version' },
		{ variableId: 'camera_id', name: 'Camera ID' },
		{ variableId: 'camera_lut', name: 'Camera LUT' },
		{ variableId: 'camera_lut_enable', name: 'Camera LUT Enable' },
		{ variableId: 'camera_pin', name: 'Camera Pin' },
		{ variableId: 'camera_runtime', name: 'Camera Runtime' },
		{ variableId: 'camera_type', name: 'Camera Type' },
		{ variableId: 'cdl_enable', name: 'CDL Enable' },
		{ variableId: 'clip_duration', name: 'Clip Duration' },
		{ variableId: 'clip_name_2', name: 'Clip Name' },
		{ variableId: 'color_space', name: 'Color Space' },
		{ variableId: 'date', name: 'Date' },
		{ variableId: 'exposure_adjust', name: 'Exposure Adjust' },
		{ variableId: 'face_detection_enable', name: 'Face Detection Enable' },
		{ variableId: 'face_detection_fallback', name: 'Face Detection Fallback' },
		{ variableId: 'face_detection_priority', name: 'Face Detection Priority' },
		{ variableId: 'false_color_enable', name: 'False Color Enable' },
		{ variableId: 'false_color_mode', name: 'False Color Mode' },
		{ variableId: 'fan_mode', name: 'Fan Mode' },
		{ variableId: 'focus_dist_far', name: 'Focus Dist Far' },
		{ variableId: 'focus_dist_mark', name: 'Focus Dist Mark' },
		{ variableId: 'focus_dist_near', name: 'Focus Dist Near' },
		{ variableId: 'frame_limit_enable', name: 'Frame Limit Enable' },
		{ variableId: 'frame_limit_frames', name: 'Frame Limit Frames' },
		{
			variableId: 'frame_limit_playback_duration',
			name: 'Frame Limit Playback Duration',
		},
		{ variableId: 'gain', name: 'Gain' },
		{ variableId: 'genlock_state', name: 'Genlock State' },
		{ variableId: 'headphone_volume', name: 'Headphone Volume' },
		{ variableId: 'language', name: 'Language' },
		{ variableId: 'lens_brand', name: 'Lens Brand' },
		{ variableId: 'lens_focal_length', name: 'Lens Focal Length' },
		{ variableId: 'lens_focus_distance', name: 'Lens Focus Distance' },
		{
			variableId: 'lens_hyperfocal_distance',
			name: 'Lens Hyperfocal Distance',
		},
		{ variableId: 'lens_is_status', name: 'Lens IS Status' },
		{ variableId: 'lens_meta_name', name: 'Lens Meta Name' },
		{ variableId: 'lens_owner', name: 'Lens Owner' },
		{ variableId: 'lens_serial_number', name: 'Lens Serial Number' },
		{ variableId: 'log_view_enable', name: 'Log View Enable' },
		{ variableId: 'media_approved_status', name: 'Media Approved Status' },
		{ variableId: 'media_capacity', name: 'Media Capacity' },
		{ variableId: 'media_clip_count', name: 'Media Clip Count' },
		{ variableId: 'media_firmware_version', name: 'Media Firmware Version' },
		{ variableId: 'media_model_number', name: 'Media Model Number' },
		{ variableId: 'media_name', name: 'Media Name' },
		{
			variableId: 'media_percentage_remaining',
			name: 'Media Percentage Remaining',
		},
		{ variableId: 'media_serial_number', name: 'Media Serial Number' },
		{ variableId: 'media_status', name: 'Media Status' },
		{ variableId: 'media_time_remaining', name: 'Media Time Remaining' },
		{ variableId: 'nd', name: 'ND' },
		{ variableId: 'nd_display', name: 'ND Display' },
		{ variableId: 'output_tone_map', name: 'Output Tone Map' },
		{ variableId: 'pdaf_stats', name: 'PD AF Stats' },
		{ variableId: 'playback_length', name: 'Playback Length' },
		{ variableId: 'playback_loop', name: 'Playback Loop' },
		{ variableId: 'playback_rate', name: 'Playback Rate' },
		{ variableId: 'playback_state', name: 'Playback State' },
		{ variableId: 'power_out_enable', name: 'Power Out Enable' },
		{ variableId: 'project_frame_rate', name: 'Project Frame Rate' },
		{
			variableId: 'prores_baked_in_settings',
			name: 'ProRes Baked In Settings',
		},
		{ variableId: 'prores_quality', name: 'ProRes Quality' },
		{ variableId: 'prores_resolution', name: 'ProRes Resolution' },
		{ variableId: 'r3d_quality', name: 'R3D Quality' },
		{ variableId: 'rcp_version', name: 'RCP Version' },
		{ variableId: 'record_codec', name: 'Record Codec' },
		{ variableId: 'record_format', name: 'Record Format' },
		{ variableId: 'record_mode', name: 'Record Mode' },
		{ variableId: 'record_state', name: 'Record State' },
		{
			variableId: 'rf_iris_compensation_enable',
			name: 'RF Iris Compensation Enable',
		},
		{ variableId: 'rf_ring_control', name: 'RF Ring Control' },
		{ variableId: 'rf_ring_enable', name: 'RF Ring Enable' },
		{ variableId: 'roll_off', name: 'Roll Off' },
		{ variableId: 'sdi_color_setting', name: 'SDI Color Setting' },
		{ variableId: 'sensor_flip_mirror', name: 'Sensor Flip Mirror' },
		{ variableId: 'sensor_frame_rate', name: 'Sensor Frame Rate' },
		{ variableId: 'tally_led_enable', name: 'Tally LED Enable' },
		{ variableId: 'time', name: 'Time' },
		{ variableId: 'timecode', name: 'Timecode' },
		{ variableId: 'tint', name: 'Tint' },
		{
			variableId: 'wifi_infrastructure_ssid',
			name: 'Wifi Infrastructure SSID',
		},
		{ variableId: 'wifi_ip_address', name: 'Wifi IP Address' },
		{ variableId: 'wifi_mac_address', name: 'Wifi MAC Address' },
		{ variableId: 'wifi_mode', name: 'Wifi Mode' },
		{ variableId: 'wifi_status', name: 'Wifi Status' },
	])
}
